apiVersion: v1
kind: ConfigMap
metadata:
  name: spendwise-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  REDIS_URL: "redis://redis-service:6379/0"
