apiVersion: v1
kind: Secret
metadata:
  name: spendwise-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@db-service:5432/{{ .Values.postgres.db }}"
