namespace: spendwise

postgres:
  image: postgres:16-alpine
  user: spendwise
  db: spendwise
  password: spendwise123
  storage: 1Gi

redis:
  image: redis:7-alpine

backend:
  image: spendwise-backend:v1
  replicas: 2
  port: 8000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
  hpa:
    minReplicas: 2
    maxReplicas: 5
    targetCPU: 50

frontend:
  image: spendwise-frontend:v1
  replicas: 2
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "150m"
      memory: "128Mi"

ingress:
  className: nginx
